# strict: true
theme:
  name: material
  # custom_dir: overrides
  # favicon: assets/favicon.png
  font:
    text: Montserrat
  # logo: assets/logo.png
  palette:
    primary: teal
    # - scheme: thrill
    #   toggle:
    #     icon: material/weather-sunny
    #     name: light mode
    # - scheme: caliente
    #   toggle:
    #     icon: material/weather-night
    #     name: dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - search.suggest

plugins:
  - search
  - roamlinks 

extra_css:
  - assets/style.css
extra_javascript:
  - assets/script.js
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes

repo_url: https://github.com/dlccyes/CollegeNotes
# logo:
site_name: El Mundo
nav:
- About: README.md

- Meta:
  - "OtherNotes/sitemap.md"

- Posts:
  - Systems and Networking:
    - "software-development/Sniffing Packets from Wireless Networks.md"
    - "software-development/restore usb bootable disk to normal disk.md"
  - DevOps:
    - "software-development/Gitlab CICD.md"
    - "software-development/GCP CICD.md"

- Software Development:
  - "software-development/Programming 101.md"
  - Languages:
    - "software-development/C++.md"
    - software-development/Python.md
    - software-development/Go.md
    - software-development/PHP.md
    - software-development/JavaScript.md
    - software-development/HTML.md
    - software-development/CSS.md
    - software-development/R.md
    - software-development/SQL.md
    - software-development/YAML.md
    - software-development/Liquid.md
    - software-development/prolog.md
    - software-development/RegEx.md
    - software-development/RISC-V.md
    - software-development/Verilog.md

  - Linux/Unix:
    - software-development/linux.md
    - OtherNotes/MacOS.md
    - software-development/WSL.md
    - software-development/Linux Package Management.md
    - software-development/shell.md
    - software-development/SSH.md
    - software-development/Makefile.md
    - software-development/base64.md
    - software-development/ANSI.md
    - software-development/PulseAudio.md
    - software-development/tcpdump.md

  - Git:
    - software-development/git.md
    - software-development/Github.md
    - software-development/Gitlab.md

  - Web:
    - software-development/Web.md
    - software-development/RESTful.md
    - Static Site Generators:
      - "software-development/Hugo.md"
      - "software-development/Jekyll.md"
    - Web Frameworks:
      - software-development/Django.md
      - software-development/Flask.md
      - software-development/Laravel.md
    - Frontend Frameworks:
      - software-development/React.md
      - software-development/Vue.md
    - API:
      - software-development/gRPC.md
      - Mocking:
        - software-development/WireMock.md

  - Databases:
    - software-development/MySQL.md
    - software-development/PostgreSQL.md
    - software-development/Redis.md
    - ORM:
      - software-development/SQLAlchemy.md

  - DevOps:
    - Domain:
      - software-development/Domain.md
      - software-development/Cloudfare.md
    - Cloud:
      - software-development/AWS.md
      - software-development/GCP.md
      - software-development/Heroku.md
      - software-development/Firebase.md
    - Containerization:
      - software-development/Docker.md
      - software-development/Kubernetes.md
    - CICD:
      - software-development/SonarQube.md
      - "software-development/Github Action.md"
      - software-development/ArgoCD.md
    - Monitoring:
      - software-development/Grafana.md

- Computer Science:
  - "OtherNotes/CS Career.md"
  - "software-development/System Design.md"
  - DSA:
    - "NTUNotes/Sophomore/Data Structure/Data Structure.md"
    - "NTUNotes/Junior/Algorithms/Algorithms.md"
    - software-development/leetcode.md
  - "NTUNotes/Junior/Computer Networks/Computer Networks.md"
  - "NTUNotes/Junior/Operating Systems/Operating Systems.md"
  - "NTUNotes/Junior/Computer Architecture/Computer Architecture.md"
  - "NTUNotes/Junior/Machine Learning/Machine Learning.md"

- Electrical Engineering:
  - "NTUNotes/Freshman/Logic Design/Logic Design.md"
  - "NTUNotes/Freshman/Circuit/Circuit.md"
  - "NTUNotes/Sophomore/Electromagnetism/Electromagnetism.md"
  - "NTUNotes/Senior/Power Engineering/Power Engineering.md"

- Economics:
  - Microeconomics:
    - "NTUNotes/Freshman/Microeconomics/README.md"
    - "NTUNotes/Freshman/Microeconomics/Ch7 Competition.md"
    - "NTUNotes/Freshman/Microeconomics/Ch8 Welfare Economics and the Gains from Trade.md"
    - "NTUNotes/Freshman/Microeconomics/Ch10 Monopoly.md"
    - "NTUNotes/Freshman/Microeconomics/Ch11 Market Power, Colusion, and Obligopoly.md"
    - "NTUNotes/Freshman/Microeconomics/Ch12 Game Theory.md"
    - "NTUNotes/Freshman/Microeconomics/Ch13 Externality.md"
    - "NTUNotes/Freshman/Microeconomics/Ch14 Common Property and Public Goods.md"
    - "NTUNotes/Freshman/Microeconomics/Ch15 The Demand for Factors of Production.md"
    - "NTUNotes/Freshman/Microeconomics/Ch16 The Market of Labor.md"
    - "NTUNotes/Freshman/Microeconomics/Ch17 Allocating Goods Over Time.md"
    - "NTUNotes/Freshman/Microeconomics/Ch18 Risk and Uncertainty.md"
  - Macroeconomics:
    - "NTUNotes/Senior/Principle of Macroeconomics/Principle of Macroeconomics.md"
    - "NTUNotes/Junior/Macroeconomics/Macroeconomics.md"
  - "NTUNotes/Senior/Statistics/Statistics.md"
  - "NTUNotes/Sophomore/Econometrics/Econometrics.md"
  - Money and Banking:
    - "NTUNotes/Sophomore/Money and Banking/README.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch2 金融體系概要.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch3 貨幣與支付系統.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch4 現值與利率.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch5 債券市場與利率的決定.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch7 金融體系的經濟分析.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch8 銀行的經營管理.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch9 台灣銀行業的結構與發展.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch11 金融安全網 最終借貸者與存款保險.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch12 金融安全網 金融機構的管制與審慎監理.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch13 中央銀行的功能與政策目標.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch14 金融穩定與總體審慎政策.md"
    - "/NTUNotes/Sophomore/Money and Banking/Ch15 準備貨幣與貨幣的創造.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch16 傳統與非傳統的貨幣政策工具.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch17 貨幣政策的目標機制.md"
    - "NTUNotes/Sophomore/Money and Banking/Ch18 貨幣政策的傳遞機制.md"
  - "NTUNotes/Freshman/Eurozone/Eurozone.md"
  - "NTUNotes/Junior/Industrial Organization/Industrial Organization.md"
  - "NTUNotes/Senior/International Finance/International Finance.md"
  - Game Theory:
    - "NTUNotes/Hung-Yu/Game Theory for Wireless Network/Game Theory.md"
    - Game Theory for Wireless Networks Papers:
      - "NTUNotes/Hung-Yu/Game Theory for Wireless Network/Coalitional Games for Computation Offloading in NOMA-Enabled Multi-Access Edge Computing.md"
      - "NTUNotes/Hung-Yu/Game Theory for Wireless Network/Opportunistic Data Collection in Cognitive Wireless  Sensor Networks - Air–Ground Collaborative Online Planning.md"
      - "NTUNotes/Hung-Yu/Game Theory for Wireless Network/privacy-preserving incentive mechanism for the federated cloud-edge learning, PFCEL.md"


# - Blog ⧉: https://dlccyes.github.io/blog

extra:
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: https://www.derricklin.net
    - icon: fontawesome/brands/medium
      link: https://blog.derricklin.net
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/derrick-lin
    - icon: fontawesome/brands/github
      link: https://github.com/dlccyes
