theme:
  name: material
  # custom_dir: overrides
  # favicon: assets/favicon.png
  font:
    text: Montserrat
  # logo: assets/logo.png
  palette:
    primary: teal
# extra_css:
# - assets/versions.css
extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
# - markdown_include.include
- codehilite
- admonition
- pymdownx.arithmatex:
    generic: true
- toc:
    permalink: true
nav:
- Overview: README.md
- Software Development:
  - Cloud:
    - software-development/AWS.md
    - software-development/GCP.md
    - software-development/Heroku.md
  - CICD:
    - software-development/Docker.md
    - software-development/Kubernetes.md
    - software-development/ArgoCD.md
    - "software-development/Github Action.md"
  - Languages:
    - "software-development/C++.md"
    - software-development/Python.md
    - software-development/Go.md
    - software-development/PHP.md
    - software-development/JavaScript.md
    - software-development/HTML.md
    - software-development/CSS.md
- Computer Science:
  - DSA:
    - "NTUNotes/Sophomore/Data Structure.md"
    - "NTUNotes/Junior/Algorithms/Algorithms.md"
  - "NTUNotes/Junior/Computer Networks.md"
  - "NTUNotes/Junior/Operating Systems.md"
  - "NTUNotes/Junior/Computer Architecture.md"
- Electrical Engineering:
  - "NTUNotes/Sophomore/Electromagnetism.md"
  - "NTUNotes/Senior/Power Engineering.md"
- Blog ⧉: https://dlccyes.github.io/blog
repo_url: https://github.com/dlccyes/dlccyes.github.io
site_name: El Mundo
# strict: true