name: gh-deploy

on:
  push:
    branches:
      - never
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container: squidfunk/mkdocs-material
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: mkdocs gh-deploy